// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ShmelJUJ/software-engineering/transaction/internal/repository (interfaces: TransactionRepo)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/transaction_repository_mocks.go github.com/ShmelJUJ/software-engineering/transaction/internal/repository TransactionRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/ShmelJUJ/software-engineering/transaction/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepo is a mock of TransactionRepo interface.
type MockTransactionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepoMockRecorder
}

// MockTransactionRepoMockRecorder is the mock recorder for MockTransactionRepo.
type MockTransactionRepoMockRecorder struct {
	mock *MockTransactionRepo
}

// NewMockTransactionRepo creates a new mock instance.
func NewMockTransactionRepo(ctrl *gomock.Controller) *MockTransactionRepo {
	mock := &MockTransactionRepo{ctrl: ctrl}
	mock.recorder = &MockTransactionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepo) EXPECT() *MockTransactionRepoMockRecorder {
	return m.recorder
}

// AcceptTransaction mocks base method.
func (m *MockTransactionRepo) AcceptTransaction(arg0 context.Context, arg1 string, arg2 *model.TransactionUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptTransaction indicates an expected call of AcceptTransaction.
func (mr *MockTransactionRepoMockRecorder) AcceptTransaction(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptTransaction", reflect.TypeOf((*MockTransactionRepo)(nil).AcceptTransaction), arg0, arg1, arg2)
}

// CancelTransaction mocks base method.
func (m *MockTransactionRepo) CancelTransaction(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTransaction indicates an expected call of CancelTransaction.
func (mr *MockTransactionRepoMockRecorder) CancelTransaction(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTransaction", reflect.TypeOf((*MockTransactionRepo)(nil).CancelTransaction), arg0, arg1, arg2)
}

// ChangeTransactionStatus mocks base method.
func (m *MockTransactionRepo) ChangeTransactionStatus(arg0 context.Context, arg1 string, arg2 model.TransactionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTransactionStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeTransactionStatus indicates an expected call of ChangeTransactionStatus.
func (mr *MockTransactionRepoMockRecorder) ChangeTransactionStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTransactionStatus", reflect.TypeOf((*MockTransactionRepo)(nil).ChangeTransactionStatus), arg0, arg1, arg2)
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepo) CreateTransaction(arg0 context.Context, arg1 *model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepoMockRecorder) CreateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepo)(nil).CreateTransaction), arg0, arg1)
}

// GetTransaction mocks base method.
func (m *MockTransactionRepo) GetTransaction(arg0 context.Context, arg1 string) (*model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1)
	ret0, _ := ret[0].(*model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionRepoMockRecorder) GetTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionRepo)(nil).GetTransaction), arg0, arg1)
}

// GetTransactionStatus mocks base method.
func (m *MockTransactionRepo) GetTransactionStatus(arg0 context.Context, arg1 string) (model.TransactionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", arg0, arg1)
	ret0, _ := ret[0].(model.TransactionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockTransactionRepoMockRecorder) GetTransactionStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockTransactionRepo)(nil).GetTransactionStatus), arg0, arg1)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionRepo) UpdateTransaction(arg0 context.Context, arg1 *model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionRepoMockRecorder) UpdateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionRepo)(nil).UpdateTransaction), arg0, arg1)
}
