logger:
  level: debug

algorand:
  algod_address: http://localhost:4001
  algod_token: "1234"
  confirmation_wait_rounds: 1
  timeout: 3s
  retries: 10
  is_test: true

kafka_subscriber:
  brokers:
    - kafka:29091
  topic_details:
    num_partitions: 1
    replication_factor: 1
  subscriber:
    pool:
      idle_timeout: 1m
      min_workers: 0
      num_workers: 100
      tasks_capacity: 1000
    processed_transaction_topic: transaction.processed
    cancelled_transaction_topic: transaction.cancelled

kafka_publisher:
  brokers:
    - kafka:29091
  publisher:
    payment_proccessing_time: 30s
    succeeded_transaction_topic: transaction.succeeded
    failed_transaction_topic: transaction.failed
    monitor_process_topic: monitor.process
