// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ShmelJUJ/software-engineering/pkg/monitor_client/models"
)

// NewProcessParams creates a new ProcessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProcessParams() *ProcessParams {
	return &ProcessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProcessParamsWithTimeout creates a new ProcessParams object
// with the ability to set a timeout on a request.
func NewProcessParamsWithTimeout(timeout time.Duration) *ProcessParams {
	return &ProcessParams{
		timeout: timeout,
	}
}

// NewProcessParamsWithContext creates a new ProcessParams object
// with the ability to set a context for a request.
func NewProcessParamsWithContext(ctx context.Context) *ProcessParams {
	return &ProcessParams{
		Context: ctx,
	}
}

// NewProcessParamsWithHTTPClient creates a new ProcessParams object
// with the ability to set a custom HTTPClient for a request.
func NewProcessParamsWithHTTPClient(client *http.Client) *ProcessParams {
	return &ProcessParams{
		HTTPClient: client,
	}
}

/*
ProcessParams contains all the parameters to send to the API endpoint

	for the process operation.

	Typically these are written to a http.Request.
*/
type ProcessParams struct {

	/* Body.

	   Information required to process a request.
	*/
	Body *models.ProcessRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the process params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProcessParams) WithDefaults() *ProcessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the process params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProcessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the process params
func (o *ProcessParams) WithTimeout(timeout time.Duration) *ProcessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the process params
func (o *ProcessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the process params
func (o *ProcessParams) WithContext(ctx context.Context) *ProcessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the process params
func (o *ProcessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the process params
func (o *ProcessParams) WithHTTPClient(client *http.Client) *ProcessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the process params
func (o *ProcessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the process params
func (o *ProcessParams) WithBody(body *models.ProcessRequest) *ProcessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the process params
func (o *ProcessParams) SetBody(body *models.ProcessRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ProcessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
